# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HF_Client_iPhone_Application' do
    
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.2.2'
    pod 'FMDB', '~> 2.7.2'
    pod 'CocoaAsyncSocket', '~> 7.6.2'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'BlocksKit', '~> 2.2.5'
    pod 'Realm', '~> 3.0.2'
    pod 'MJExtension', '~> 3.0.13'
    pod 'TXLiteAVSDK_Smart', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_Smart.podspec'
    #pod 'SDCycleScrollView','~> 1.64'
    #pod 'UMengAnalytics'
    #pod 'SAMKeychain'
    
end

    #pod 'TXLiteAVSDK_UGC', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_UGC.podspec'
    #pod 'TXLiteAVSDK_Player', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_Player.podspec'
    #pod 'TXLiteAVSDK_Professional', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_Professional.podspec'
    #pod 'TXLiteAVSDK_Professional_Rename', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_Professional_Rename.podspec'

