# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HF_Client_iPhone_Application' do
    
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.2.2'
    pod 'FMDB', '~> 2.7.2'
    pod 'CocoaAsyncSocket', '~> 7.6.2'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'BlocksKit', '~> 2.2.5'
    #pod 'SDCycleScrollView','~> 1.64'
    #pod 'UMengAnalytics'
    #pod 'SAMKeychain'
    
end
